const { default: expect } = require('expect');
const calculateStrikeRateForABatsman = require('../src/server/7-striike-rate-of-a-batsman-per-ssn');

const matchesTest = [
  {
    id: '3',
    season: '2016',
    city: 'Kolkata',
    team1: 'Mumbai Indians',
    team2: 'Chennai Super Kings',
    winner: 'Mumbai Indians',
  },
  {
    id: '5',
    season: '2016',
    city: 'Mumbai',
    team1: 'Mumbai Indians',
    team2: 'Chennai Super Kings',
    winner: 'Chennai Super Kings',
  },
  {
    id: '58',
    season: '2012',
    city: 'Kolkata',
    team1: 'Mumbai Indians',
    team2: 'Chennai Super Kings',
    winner: 'Mumbai Indians',
  },
  {
    id: '80',
    season: '2012',
    city: 'Kolkata',
    team1: 'Mumbai Indians',
    team2: 'Chennai Super Kings',
    winner: 'Chennai Super Kings',
  },
];

const deliveriesTest = [
  {
    match_id: '3',
    inning: '2',
    batting_team: 'Chennai Super Kings',
    bowling_team: 'Mumbai Indians',
    over: '18',
    ball: '4',
    batsman: 'MS Dhoni',
    non_striker: 'Suresh Raina',
    bowler: 'J Bumrah',
    is_super_over: '0',
    wide_runs: '0',
    bye_runs: '0',
    legbye_runs: '0',
    noball_runs: '0',
    penalty_runs: '0',
    batsman_runs: '0',
    extra_runs: '0',
    total_runs: '0',
    player_dismissed: '',
    dismissal_kind: '',
    fielder: '',
  },
  {
    match_id: '3',
    inning: '2',
    batting_team: 'Chennai Super Kings',
    bowling_team: 'Mumbai Indians',
    over: '18',
    ball: '5',
    batsman: 'MS Dhoni',
    non_striker: 'Suresh Raina',
    bowler: 'J Bumrah',
    is_super_over: '0',
    wide_runs: '0',
    bye_runs: '0',
    legbye_runs: '0',
    noball_runs: '0',
    penalty_runs: '0',
    batsman_runs: '4',
    extra_runs: '0',
    total_runs: '4',
    player_dismissed: '',
    dismissal_kind: '',
    fielder: '',
  },
  {
    match_id: '5',
    inning: '1',
    batting_team: 'Chennai Super Kings',
    bowling_team: 'Mumbai Indians',
    over: '20',
    ball: '1',
    batsman: 'MS Dhoni',
    non_striker: 'R Jadeja',
    bowler: 'T Boult',
    is_super_over: '0',
    wide_runs: '0',
    bye_runs: '0',
    legbye_runs: '0',
    noball_runs: '0',
    penalty_runs: '0',
    batsman_runs: '6',
    extra_runs: '0',
    total_runs: '6',
    player_dismissed: '',
    dismissal_kind: '',
    fielder: '',
  },
  {
    match_id: '58',
    inning: '2',
    batting_team: 'Chennai Super Kings',
    bowling_team: 'Mumbai Indians',
    over: '12',
    ball: '2',
    batsman: 'MS Dhoni',
    non_striker: 'Suresh Raina',
    bowler: 'Malinga',
    is_super_over: '0',
    wide_runs: '0',
    bye_runs: '0',
    legbye_runs: '1',
    noball_runs: '0',
    penalty_runs: '0',
    batsman_runs: '0',
    extra_runs: '0',
    total_runs: '1',
    player_dismissed: '',
    dismissal_kind: '',
    fielder: '',
  },
  {
    match_id: '80',
    inning: '1',
    batting_team: 'Chennai Super Kings',
    bowling_team: 'Mumbai Indians',
    over: '16',
    ball: '3',
    batsman: 'MS Dhoni',
    non_striker: 'AM Rayudu',
    bowler: 'J Bumrah',
    is_super_over: '0',
    wide_runs: '0',
    bye_runs: '0',
    legbye_runs: '0',
    noball_runs: '0',
    penalty_runs: '0',
    batsman_runs: '1',
    extra_runs: '0',
    total_runs: '1',
    player_dismissed: '',
    dismissal_kind: '',
    fielder: '',
  },
];

const expected = { 2012: '50.00', 2016: '333.33' };

test('Returns the strike rate per season of a batsman', () => {
  expect(
    calculateStrikeRateForABatsman(matchesTest, deliveriesTest, 'MS Dhoni'),
  ).toEqual(expected);
});
